- name: Add suricata ppa repo
  become: true
  ansible.builtin.apt_repository:
    filename: suricata_repo
    repo: "ppa:oisf/suricata-stable"
    state: present
    update_cache: true
  when: suricata_use_ppa | bool

- name: Install suricata
  become: true
  ansible.builtin.apt:
    name: suricata
    state: present

- name: Ensure custom rule folder exists
  become: true
  ansible.builtin.file:
    path: "{{ suricata_rule_path }}"
    state: directory

- name: Add custom rule files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ suricata_rule_path }}/{{ item | basename }}"
    mode: "0644"
    owner: root
    group: root
  loop: "{{ suricata_extra_rule_files }}"
  notify: Restart suricata

- name: Configure default file
  become: true
  ansible.builtin.template:
    src: "{{ suricata_default_tpl }}"
    dest: "/etc/default/suricata"
    mode: "0644"
    owner: "root"
    group: "root"
  notify: Restart suricata

- name: Configure surciata
  become: true
  ansible.builtin.template:
    src: "{{ suricata_tpl }}"
    dest: "/etc/suricata/suricata.yaml"
    mode: "0644"
    owner: "root"
    group: "root"
  notify: Restart suricata

- name: Start service suricata, if not started
  become: true
  ansible.builtin.service:
    name: suricata
    state: started
